const members=[
 {id:'james',name:'赵雨凡',en:'James',role:'领舞 · 领唱',tone:'礼貌温和，细致而克制'},
 {id:'juhoon',name:'金主训',en:'Juhoon',role:'主舞 · Rapper',tone:'冷感直接，情绪写在眼里'},
 {id:'martin',name:'马丁',en:'Martin',role:'队长 · 制作人',tone:'沉稳控场，敏锐又真诚'},
 {id:'seong',name:'严成玹',en:'Seonghyeon',role:'主唱',tone:'嘴硬心细，镜头感十足'},
 {id:'keonho',name:'安乾镐',en:'Keonho',role:'副唱 · 忙内',tone:'安静真诚，笑眼很亮'}
];
const $=s=>document.querySelector(s); const state={turn:0,time:468,chosen:[],stats:{mood:70,popularity:32,money:18000,secrecy:100,alertness:18,pressure:52,impulse:28},affection:{},player:{},cg:0};
const picker=$('#member-picker');
picker.innerHTML=members.map((m,i)=>`<label class="member-card" data-index="0${i+1}"><input type="checkbox" value="${m.id}"><span><strong>${m.name}</strong><small>${m.en} · ${m.role}</small></span></label>`).join('');
$('#player-job').addEventListener('change',e=>$('#custom-job-wrap').hidden=e.target.value!=='custom');
$('#setup-form').addEventListener('submit',e=>{e.preventDefault();const chosen=[...document.querySelectorAll('.member-card input:checked')].map(x=>x.value);if(!chosen.length){alert('请至少选择一位故事主角。');return}state.chosen=chosen;state.player={name:$('#player-name').value.trim(),age:$('#player-age').value,country:$('#player-country').value.trim(),traits:$('#player-traits').value.trim(),job:$('#player-job').value==='custom'?$('#custom-job').value.trim():$('#player-job').value,style:$('#player-style').value.trim()};chosen.forEach(id=>state.affection[id]=18);localStorage.setItem('cortis-save',JSON.stringify(state));$('#onboarding').hidden=true;$('#story').hidden=false;renderTurn('start')});
function selected(){return state.chosen.map(id=>members.find(m=>m.id===id))}function clock(){return `${String(Math.floor(state.time/60)).padStart(2,'0')}:${String(state.time%60).padStart(2,'0')}`}function place(){return state.turn<2?'HYBE 练习室 B':state.turn<4?'制作楼层的自动贩卖机前':'汉江边的外景拍摄地'}
function renderTurn(mode,action){state.turn++;state.time+=mode==='start'?0:25;const leads=selected(),lead=leads[(state.turn-1)%leads.length],other=members.find(m=>!state.chosen.includes(m.id));let text,phone='';
 if(state.turn===1){text=`<p>练习室的门在身后合上，低频的鼓点还从隔壁漏进来。你抱着刚领到的彩排物料，鞋底在木地板上停了一下。</p><p>镜墙前，<span class="speaker">${lead.name}（${lead.en}）</span>抬手关掉音响。他额前的碎发被汗水压出弯曲的弧度，视线越过其余成员，落在你怀里那叠印着时间表的纸上。</p><p class="quote">“这里下午一点之后排给 CORTIS。”他把毛巾搭到肩上，声音压得很轻，“你是来彩排的？”</p><p>角落里的经纪人正低头回工作群；门外有人推着器材箱经过。这个空间并不适合长谈，却也还没有人催你离开。</p>`;}
 else {const cue=action||'你没有急着靠近，只把自己的事做完'; const curious=state.turn%3===0; text=`<p>${cue}。走廊另一头的感应灯依次亮起，冷白的光落在你们脚边，像把短暂的停留切成几段。</p><p><span class="speaker">${lead.name}（${lead.en}）</span>没有立刻接话。他先看了一眼不远处的工作人员，又把手里拧开的矿泉水放到窗台上，才向你靠近半步。</p><p class="quote">“你刚才说的，我记住了。”他指尖在瓶身上停住，抬眼时神情很稳，“只是这里人多，别让人误会你是特意为谁来的。”</p>${curious?`<p>手机在他掌心亮了一下。屏幕上是一条来自工作群的提醒：外景拍摄的集合时间提前。${other.name}从转角探出头，朝这边晃了晃通行证，像是无意地打断了这段安静。</p>`:''}`;if(state.turn===2)phone=`<div class="phone-head">KKT · 新消息</div><div class="bubble"><small>▢ ${lead.name}　${clock()}</small>到家之后说一声。不是催你，只是今天外面风很大。</div>`}
 $('#day-label').textContent='周二';$('#time-label').textContent=clock();$('#place-label').textContent=place();$('#narrative').innerHTML=text;$('#phone-card').hidden=!phone;$('#phone-card').innerHTML=phone; renderChoices(lead); renderStats([]);window.scrollTo({top:0,behavior:'smooth'});}
function renderChoices(lead){const options=[['A','回应他','把话题留在工作范围内，礼貌而清楚地回应。'],['B','继续做自己的事','整理物料，把空间还给正在休息的成员。'],['C','轻轻试探','用一句不越界的玩笑，看看他的反应。'],['D','先离开','以时间表为由告别，避免停留太久。']];$('#choice-list').innerHTML=options.map(([key,title,detail])=>`<button class="choice" data-action="${title}：${detail}"><b>${key}</b>${title}<br><span style="padding-left:28px;color:#9b97a2;font-size:11px">${detail}</span></button>`).join('');document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>applyChoice(b.dataset.action,lead));}
function applyChoice(action,lead){const plus=action.startsWith('回应')||action.startsWith('轻轻');const delta=plus?2:1;state.affection[lead.id]+=delta;state.stats.mood+=1;if(action.startsWith('轻轻')){state.stats.alertness+=1;state.stats.impulse+=2}localStorage.setItem('cortis-save',JSON.stringify(state));renderTurn('choice',action);renderStats([`${lead.name}（${lead.en}）好感 <b>+${delta}</b>`,action.startsWith('轻轻')?'公司警觉度 <b>+1</b>':'心情值 <b>+1</b>']);}
$('#custom-toggle').onclick=()=>$('#custom-action').hidden=!$('#custom-action').hidden;$('#custom-send').onclick=()=>{const v=$('#custom-input').value.trim();if(v)applyChoice(v,selected()[0]);};
function renderStats(deltas){$('#delta-list').innerHTML=deltas.length?deltas.map(d=>`<div class="delta">${d}</div>`).join(''):'<div class="delta">无</div>';}
$('#back-btn').onclick=()=>{if(confirm('返回会结束本次未保存的页面状态。'))location.reload()};$('#save-btn').onclick=()=>{localStorage.setItem('cortis-save',JSON.stringify(state));alert('进度已保存在本机。')};
const dialog=$('#panel-dialog');$('#close-dialog').onclick=()=>dialog.close();document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.panel==='story')return;const profile=b.dataset.panel==='profile';$('#dialog-content').innerHTML=profile?`<h2 class="dialog-title">你的档案</h2>${[['姓名',state.player.name],['年龄',state.player.age],['职业',state.player.job],['性格',state.player.traits],['主角',selected().map(x=>x.name).join('、')]].map(x=>`<div class="profile-row"><span>${x[0]}</span>${x[1]}</div>`).join('')}`:`<h2 class="dialog-title">故事数值</h2><div class="stat-grid">${[['人气值',state.stats.popularity],['心情值',state.stats.mood],['金钱','₩'+state.stats.money.toLocaleString()],['保密度',state.stats.secrecy],['公司警觉',state.stats.alertness],['事业压力',state.stats.pressure],['越线冲动',state.stats.impulse],['解锁 CG',state.cg]].map(x=>`<div class="stat-box">${x[0]}<b>${x[1]}</b></div>`).join('')}</div><h3 style="font-size:13px;margin-top:20px">好感度</h3>${selected().map(x=>`<div class="profile-row"><span>${x.name}</span>${state.affection[x.id]} · 有印象</div>`).join('')}`;dialog.showModal()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
